### ISSUE TITLE
There is no .exe file

### ISSUE THREAD

**Issue by YourMajestyTheEye** [iwannet/Admin-Exe-Installer#1]
### Describe the feature

what does it mean by "enter the path to your exe file"?

### Before submitting a suggestion

- [x] This feature doesn't already exist.

- [X] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by iwannet** [comment]
When you try to install an app, you need to download the app first, you download an .exe file. For example:  google-chrome-xxx.exe or something.

You need to enter the path to that file. For example when the .exe file is in the download folder, enter as path:   C:/Users/{yourusername}/Downloads/{your-exefile}.exe

To get the path of an file you can do this:

Shift + Right-Click the file -> Copy As Path
